name: Yaml Lint
on: [pull_request]
jobs:
  lint:
    name: Run yaml linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .github/.yamllint
